#### DATABASE
db:
  dbpath: '{FILL ME}' # Path to sqlite files
  merge: false
#### DISPLAY
display:
  path: '{FILL ME}' # Path to images
  nimages: 1200 #Number of objects to be displayed even if there are more in the folder
  xdim: 40 #X dimension for the display
  ydim: 30 #Y dimension for the display
  tileSize: 256 #Size of the tile for which images are resized at max zoom level
  minXrange: 0
  minYrange: 0
  deltaZoom: 5 #default == 5
  min-width: 500
  max-width: 1400
  min-height: 500
  max-height: 1000
#### SERVER
server:
  ssl: false #use ssl, need to have certificates
  sslName: test #prefix of .crt and .key files inside ssl/ folder e.g., ssl/{sslName.key}
  host: 'http://localhost' #if using ssl, change to https
  port: 8888
  rootUrl: '/' #root url for server, e.g. request are made to /cexp/, if None use "/"
  #workers: None # None will default to the workers in the machine
#### CLIENT
client:
  host: 'http://localhost'
  port: 8000
#### OPERATIONS options
operation:
  updates: false #allows to update and/or remove classes to images, false and classes are fixed.
  help: true
  fullscreen: true
  invert: true
  toggle-classes: true
  random: true
  filter: true
  reset: true
  search: true
#### CLASSES
#### classes, use any classes from 0 to 9, class 0 is for hidden! class -1 is no class
classes:
    - Test: 5
