classes:
- Delete: 0
client:
  host: http://localhost
  port: 8081
db:
  dbpath: dbpath
  merge: false
display:
  deltaZoom: 3
  minXrange: 0
  minYrange: 0
  nimages: 1200
  path: /home/matias/Research/ghost/fakes/images
  tileSize: 256
  xdim: 50
  ydim: 30
operation:
  updates: false
server:
  host: http://localhost
  port: 8889
  rootUrl: /
  ssl: false
  sslName: test
